services:
  app-service:
    image: mass1023/app-service # specify name of image on Docker Hub
    # restart: "always" # automatically restart container when server crashes
    environment: # set up environment variables
      AUTH_SERVICE_IP: ${AUTH_SERVICE_IP:-localhost} # Use localhost as the default value
    ports:
      - "8000:8000" # expose port 8000 so that applications outside the container can connect to it
    depends_on: # only run app-service after auth-service has started
      auth-service:
        condition: service_started
  auth-service:
    image: mass1023/auth-service
    # restart: "always" # automatically restart container when server crashes
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: "postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-appdb}"
    ports:
      - "3000:3000" # expose port 3000 so that applications outside the container can connect to it
    depends_on: # only run auth-service after db has started
      - db
  db:
    image: postgres:15.2-alpine # use official Postgres image from Docker Hub
    restart: "always" # automatically restart container when server crashes
    environment: # set up environment variables for Postgres
      POSTGRES_USER: ${POSTGRES_USER:-admin} # default username is 'admin'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password} # default password is 'password'
      POSTGRES_DB: ${POSTGRES_DB:-appdb} # default database name is 'appdb'
    ports:
      - "5432:5432" # expose port 5432 so that applications outside the container can connect to it
    volumes:
      - db-data:/var/lib/postgresql/data # persist database data in a Docker volume
  redis:
    image: redis:7.0-alpine # use official Redis image from Docker Hub
    restart: "always" # automatically restart container when server crashes
    ports:
      - "6379:6379" # expose port 6379 so that applications outside the container can connect to it
volumes:
  db-data: # named volume for Postgres data persistence
    driver: local
